### ISSUE TITLE
POST/PUT - Transfer tokens endpoint

### ISSUE THREAD

**Issue by SuspenseFallback** [Greenstand/POS-Shopify-Extension#64]
# API issue

**Version**: MVP v0

**CRUD type**: POST/PUT

- Transfer tokens from Linked Greenstand wallet to consumer wallet

## Expected behaviour

- Tokens are transferred (might need to accept)

## Need help?

- Ask here!
- Look at the Shopify documentation!
- Message Krithin Jay on Slack!

**Comment by XLPeng57** [comment]
@SuspenseFallback Could you assign this to me? Thank you!

**Comment by SuspenseFallback** [comment]
Hi, yes I will. Sorry about the late response!

**Comment by XLPeng57** [comment]
> Hi, yes I will. Sorry about the late response!

Thank you Krithin!

**Comment by SuspenseFallback** [comment]
Hi @XLPeng57 , how is this issue going?

**Comment by XLPeng57** [comment]
Hi @SuspenseFallback! I’ve already added endpoints to initiate and accept token transfers, but I’m not sure how to test them. I'm also confused about the step at which we should transfer tokens to the consumer. I thought the token should be transferred when the consumer has successfully placed an order and created or linked their treetracker wallet. However, since our `create-wallet` feature isn't working right now, I cannot retrieve the consumer’s wallet name, so I just stopped here.
I just created a draft pull request. Please review it when you have time. I’m not sure what I should do next.

**Comment by SuspenseFallback** [comment]
Oh yes, thank you very much!
